In [16]:
import matplotlib.pyplot as plt
import numpy as np

# Activez ces 2 lignes pour afficher le graphique en 3D dans une fenetre.
import matplotlib
matplotlib.use('TkAgg') 

# Création d'un plan

Ici, nous allons tracer un plan, c'est-a-dire calculer le résultat d'une fonction linéaire:
$$f(x_1, x_2) = w_1 x_1 + w_2 x_2 + b$$

toutes les valeurs ($x_1, x_2$) de l'espace.




![alt text](meshgrid.png "Title")

Pour cela, on utilise une Meshgrid afin de créer les tableaux suivants :

In [32]:
min_born=-10
max_born=10
x1 = np.arange(min_born,max_born, 1)
x2 = np.arange(min_born, max_born, 1)

x1

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [33]:
x1_grid, x2_grid = np.meshgrid(x1, x2)

In [34]:
x1_grid

array([[-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5,   6,   7,   8,   9],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,  

In [35]:
x2_grid

array([[-10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10,
        -10, -10, -10, -10, -10, -10, -10],
       [ -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,
         -9,  -9,  -9,  -9,  -9,  -9,  -9],
       [ -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,
         -8,  -8,  -8,  -8,  -8,  -8,  -8],
       [ -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,  -7,
         -7,  -7,  -7,  -7,  -7,  -7,  -7],
       [ -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,
         -6,  -6,  -6,  -6,  -6,  -6,  -6],
       [ -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,
         -5,  -5,  -5,  -5,  -5,  -5,  -5],
       [ -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,
         -4,  -4,  -4,  -4,  -4,  -4,  -4],
       [ -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,  -3,
         -3,  -3,  -3,  -3,  -3,  -3,  -3],
       [ -2,  -2,  -2,  -2,  -2,  -2,  -2,  -2,  -2,  -2,  -2,  

On peut ensuite utiliser x1_grid et x2_grid pour effectuer nos calculs.

In [36]:
w1 = 0.7
w2 = 0.5
b = 8

f = w1 * x1_grid + w2 * x2_grid + b

f

array([[-4. , -3.3, -2.6, -1.9, -1.2, -0.5,  0.2,  0.9,  1.6,  2.3,  3. ,
         3.7,  4.4,  5.1,  5.8,  6.5,  7.2,  7.9,  8.6,  9.3],
       [-3.5, -2.8, -2.1, -1.4, -0.7,  0. ,  0.7,  1.4,  2.1,  2.8,  3.5,
         4.2,  4.9,  5.6,  6.3,  7. ,  7.7,  8.4,  9.1,  9.8],
       [-3. , -2.3, -1.6, -0.9, -0.2,  0.5,  1.2,  1.9,  2.6,  3.3,  4. ,
         4.7,  5.4,  6.1,  6.8,  7.5,  8.2,  8.9,  9.6, 10.3],
       [-2.5, -1.8, -1.1, -0.4,  0.3,  1. ,  1.7,  2.4,  3.1,  3.8,  4.5,
         5.2,  5.9,  6.6,  7.3,  8. ,  8.7,  9.4, 10.1, 10.8],
       [-2. , -1.3, -0.6,  0.1,  0.8,  1.5,  2.2,  2.9,  3.6,  4.3,  5. ,
         5.7,  6.4,  7.1,  7.8,  8.5,  9.2,  9.9, 10.6, 11.3],
       [-1.5, -0.8, -0.1,  0.6,  1.3,  2. ,  2.7,  3.4,  4.1,  4.8,  5.5,
         6.2,  6.9,  7.6,  8.3,  9. ,  9.7, 10.4, 11.1, 11.8],
       [-1. , -0.3,  0.4,  1.1,  1.8,  2.5,  3.2,  3.9,  4.6,  5.3,  6. ,
         6.7,  7.4,  8.1,  8.8,  9.5, 10.2, 10.9, 11.6, 12.3],
       [-0.5,  0.2,  0.9,  1.6,  2.3,  3.

In [37]:
# Plotting
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# plot the plane
ax.plot_surface(x1_grid, x2_grid, f, alpha=0.6, color='Blue', edgecolor='none')

# Set axis limits
# ax.set_xlim(-10, 10)
# ax.set_ylim(-10, 10)
# ax.set_zlim(-10, 10)

# Draw axes through origin
ax.plot([-10, 10], [0, 0], [0, 0], color='black')  # x-axis
ax.plot([0, 0], [-10, 10], [0, 0], color='black')  # y-axis
ax.plot([0, 0], [0, 0], [-10, 10], color='black')  # z-axis

plt.tight_layout()
plt.show()


# Fonction `MSE`


In [23]:
np.random.seed(0)

X = np.linspace(0, 10, 20)

true_w, true_b = 2, 1

y = true_w * X + true_b + np.random.normal(scale=2, size=X.shape)

plt.scatter(X, y, s=20)

In [24]:
w, b = 0.7, 5

y_pred = w * X + b # modele linéaire

In [25]:
plt.scatter(X, y, color="blue", s=50)

plt.plot(X, y_pred, color="green")

### calcul de la `MSE`

$$MSE(w, b) = \frac{1}{m} \sum_i (y^{(i)} - w \times {x}^{(i)} + b)^2$$

In [26]:
mse = 1 / len(y) * np.sum((y - y_pred)**2)
mse

np.float64(26.250232788045167)

In [27]:
plt.scatter(X, y, color="blue")

plt.plot(X, y_pred, color="green")

for xi, yi, ypi in zip(X, y, y_pred):
    plt.plot([xi, xi], [yi, ypi], 'r--')  # ligne pointillée rouge

plt.show()

### Visualisation de la `MSE` avec Meshgrid

In [28]:
W_vals = np.linspace(0, 3, 50)
B_vals = np.linspace(-1, 3, 50)

W, B = np.meshgrid(W_vals, B_vals)

In [29]:
MSE = np.zeros_like(W)

for i in range(W.shape[0]):
    for j in range(W.shape[1]):
        y_hat = W[i, j] * X + B[i, j]
        MSE[i, j] = np.mean((y - y_hat) ** 2)


fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(W, B, MSE, cmap='viridis', edgecolor='none')

# ax.set_xlabel('w')
# ax.set_ylabel('b')
# ax.set_zlabel('MSE')
# ax.set_title("Surface de l'erreur quadratique moyenne (MSE)")
plt.show()

In [30]:
# Pour voir cette fonction en vue du dessus :
plt.contourf(W, B, MSE)